require "csv"
require "date"
require "bigdecimal"
require "./lib/merchant"
require_relative "../lib/merchant_repository"
require "./lib/item"
require "./lib/item_repository"
require "./lib/sales_engine"
require "./lib/sales_analyst"
require "./lib/invoice"
require "./lib/invoice_repository"
require "./lib/invoice_item"
require "./lib/invoice_item_repository"
require "./lib/transaction"
require "./lib/transaction_repository"
require "./lib/customer"
require "./lib/customer_repository"
# require the stupid fucking modules here because ruby is too fucking stupid to fucking find them